
name: Automatically clock
on:
  workflow_dispatch:
  schedule:
    # 北京时间是 UTC+8 时区，所以如果想在北京时间 00:05 打卡，就需要把定时任务设置在 16:05 (UTC)
    - cron: '55 20 * * *'
    
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: python -m pip install -r requirements.txt 
    - shell: bash
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        LONGITUDE: ${{secrets.longtitude}}
        LATITUDE: ${{secrets.latitude}}
      run: python ncov.py -username="$USERNAME" -password="$PASSWORD" -longitude="$LONGITUDE" -latitude="$LATITUDE"
